---
deployment_type: automationhub

worker:
  replicas: 2
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 4Gi

is_file_storage: true

# Here we use  _automationhub_ansible_com_automationhub to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_automationhub_ansible_com_automationhub']['spec'] }}"
