presubmits:
- name: pull-test-infra-yamllint
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
    command:
    - .ci/prow/openshift-test.sh
