presubmits:
- name: pull-test-infra-yamllint
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/operator_testing/operator-test-playbooks
      command:
      - .ci/prow/openshift-test.sh
