# test
presets:
- labels:
    preset-test: "true"
  env:
  - name: KUBECONFIG
    value: /etc/kubeconfig/config
  volumes:
  - name: kubeconfig
    secret:
      defaultMode: 0644
      secretName: kubeconfig
  volumeMounts:
  - name: kubeconfig
    mountPath: /etc/kubeconfig
    readonly: true

presubmits:
- name: prow-build-image
  labels:
    preset-test: "true"
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/build-ocp-image.sh
- name: prow-operator-ocp-deploy
  labels:
    preset-test: "true"
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/openshift-test.sh
- name: prow-operator-ocp-checks
  labels:
    preset-test: "true"
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/check-deployment.sh
- name: prow-operator-ocp-uninstall
  labels:
    preset-test: "true"
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/uninstall.sh
