presubmits:
- name: pull-test-infra-yamllint
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/fedora/fedora
      command:
      - make
      - bundle
