# test
presubmits:
- name: prow-build-image
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/build-ocp-image.sh
      volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
        readOnly: true
    volumes:
    - name: kubeconfig
      secret:
        defaultMode: 0644
        secretName: kubeconfig # example above contains a `config` key
- name: prow-operator-ocp-deploy
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/openshift-test.sh
      volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
        readOnly: true
    volumes:
    - name: kubeconfig
      secret:
        defaultMode: 0644
        secretName: kubeconfig # example above contains a `config` key
- name: prow-operator-ocp-checks
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/check-deployment.sh
      volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
        readOnly: true
    volumes:
    - name: kubeconfig
      secret:
        defaultMode: 0644
        secretName: kubeconfig # example above contains a `config` key
- name: prow-operator-ocp-uninstall
  always_run: true
  decorate: true
  skip_report: false
  spec:
    containers:
    - image: quay.io/rhn_support_hyagi/prow-test:latest
      command:
      - .ci/prow/uninstall.sh
      volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
        readOnly: true
    volumes:
    - name: kubeconfig
      secret:
        defaultMode: 0644
        secretName: kubeconfig # example above contains a `config` key
