---
- name: pulp-content service
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-content

- name: Set default pulp-content image
  set_fact:
    _default_image: "{{ _image }}:{{ _image_version }}"

- name: Set user provided pulp-content image
  set_fact:
    _custom_image: "{{ image }}:{{ image_version }}"
  when:
    - image is defined and image != ''
    - image_version is defined and image_version != ''

- name: Set pulp-content image URL
  set_fact:
    _image: "{{ _custom_image | default(lookup('env', 'RELATED_IMAGE_HUB')) | default(_default_image, true) }}"

- name: Set node affinity
  set_fact:
    _node_affinity: "{{ raw_spec['affinity']['node_affinity'] | default({}) }}"
  when: affinity is defined and affinity.node_affinity is defined

- name: pulp-content deployment
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-content
