---

- name: Load Route TLS certificate
  include_tasks: load_route_tls_secret.yml
  when:
    - ingress_type | lower == 'route'
    - route_tls_secret != ''

- name: pulp-web configmap
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.configmap.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-web

- name: Set default pulp-web image
  set_fact:
    _default_image_web: "{{ _image_web }}:{{ _image_web_version }}"

- name: Set user provided pulp-web image
  set_fact:
    _custom_image_web: "{{ image_web }}:{{ image_web_version }}"
  when:
    - image_web is defined and image_web != ''
    - image_web_version is defined and image_web_version != ''

- name: Set pulp-web image URL
  set_fact:
    _image_web: "{{ _custom_image_web | default(lookup('env', 'RELATED_IMAGE_HUB_WEB')) | default(_default_image_web, true) }}"

- name: Set node affinity
  set_fact:
    _node_affinity: "{{ raw_spec['affinity']['node_affinity'] | default({}) }}"
  when: affinity is defined and affinity.node_affinity is defined

- name: pulp-web deployment
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-web

- name: pulp-web service
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml.j2') | from_yaml }}"
  with_items:
    - pulp-web
