---
_redis_image: redis:latest

redis_resource_requirements:
  requests:
    cpu: 200m
    memory: 512Mi

# Here we use  _automationhub_ansible_com_automationhub to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_automationhub_ansible_com_automationhub']['spec'] }}"
